python: can't open file '/tmp/gptme-evals-hkugts51/hello.py': [Errno 2] No such file or directory
