python: can't open file '/tmp/gptme-evals-0rxpuu94/prime.py': [Errno 2] No such file or directory
