python: can't open file '/tmp/gptme-evals-pa_bkglf/prime.py': [Errno 2] No such file or directory
