python: can't open file '/tmp/gptme-evals-cpmwb0dn/prime.py': [Errno 2] No such file or directory
