python: can't open file '/tmp/gptme-evals-fwp6te2y/hello.py': [Errno 2] No such file or directory
