python: can't open file '/tmp/gptme-evals-6s73fa7x/prime.py': [Errno 2] No such file or directory
