python: can't open file '/tmp/gptme-evals-gw95_15s/prime.py': [Errno 2] No such file or directory
