python: can't open file '/tmp/gptme-evals-k8v15wa7/prime.py': [Errno 2] No such file or directory
