python: can't open file '/tmp/gptme-evals-1gy1n3oz/hello.py': [Errno 2] No such file or directory
