python: can't open file '/tmp/gptme-evals-o65irs8n/hello.py': [Errno 2] No such file or directory
