python: can't open file '/tmp/gptme-evals-_qbo_26w/hello.py': [Errno 2] No such file or directory
