python: can't open file '/tmp/gptme-evals-0p02tawf/prime.py': [Errno 2] No such file or directory
