python: can't open file '/tmp/gptme-evals-mii87qm2/hello.py': [Errno 2] No such file or directory
