python: can't open file '/tmp/gptme-evals-g0j8dzx9/prime.py': [Errno 2] No such file or directory
