python: can't open file '/tmp/gptme-evals-p1uxe96r/prime.py': [Errno 2] No such file or directory
