python: can't open file '/tmp/gptme-evals-76780dx1/prime.py': [Errno 2] No such file or directory
