python: can't open file '/tmp/gptme-evals-n5p46v23/prime.py': [Errno 2] No such file or directory
