python: can't open file '/tmp/gptme-evals-su2pr2vr/prime.py': [Errno 2] No such file or directory
