python: can't open file '/tmp/gptme-evals-7u04w6rh/prime.py': [Errno 2] No such file or directory
