python: can't open file '/tmp/gptme-evals-lx2un0qk/prime.py': [Errno 2] No such file or directory
