python: can't open file '/tmp/gptme-evals-o4qatwtf/hello.py': [Errno 2] No such file or directory
