python: can't open file '/tmp/gptme-evals-kd72hxcr/hello.py': [Errno 2] No such file or directory
