python: can't open file '/tmp/gptme-evals-a93j6az8/prime.py': [Errno 2] No such file or directory
