python: can't open file '/tmp/gptme-evals-f68oez_m/hello.py': [Errno 2] No such file or directory
