python: can't open file '/tmp/gptme-evals-f6ptbc06/prime.py': [Errno 2] No such file or directory
