python: can't open file '/tmp/gptme-evals-1kis6t5_/hello.py': [Errno 2] No such file or directory
