python: can't open file '/tmp/gptme-evals-euueqfni/prime.py': [Errno 2] No such file or directory
