python: can't open file '/tmp/gptme-evals-1s1m47nn/prime.py': [Errno 2] No such file or directory
