python: can't open file '/tmp/gptme-evals-gqpm6j0f/hello.py': [Errno 2] No such file or directory
