python: can't open file '/tmp/gptme-evals-9vzibdab/hello.py': [Errno 2] No such file or directory
